# Generated by Django 3.2.7 on 2021-09-23 17:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_moderator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='online_tracker', serialize=False, to='users.user')),
                ('last_click', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
