# Generated by Django 3.2.7 on 2021-09-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online_presence_hidden',
            field=models.BooleanField(default=False, verbose_name='Is Online presence hidden?'),
        ),
    ]
