# Generated by Django 3.2.7 on 2021-10-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last',
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Full name'),
        ),
    ]
