# Generated by Django 3.2.7 on 2021-10-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_email_hashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_hashed',
            field=models.CharField(blank=True, max_length=425, null=True, verbose_name='e-mail hashed'),
        ),
    ]
