# Generated by Django 3.2.7 on 2021-10-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_email_hashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='updated',
        ),
    ]
