# Generated by Django 3.2.7 on 2021-10-04 10:20

import dev.invitation.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=dev.invitation.models.get_default_uuid, editable=False, max_length=32, unique=True)),
                ('invite_to_user_email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('invite_token', models.CharField(blank=True, max_length=15, null=True, verbose_name='Token')),
                ('message', models.TextField(blank=True, max_length=225, null=True, verbose_name='Message')),
                ('status', models.CharField(blank=True, choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('expired', 'Expired')], max_length=10, null=True, verbose_name='Invite Status')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('invite_from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites_from_user', to=settings.AUTH_USER_MODEL, verbose_name='invitation from user')),
                ('invite_to_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': "Invitation's",
                'ordering': ('-created_date',),
                'unique_together': {('invite_from_user', 'invite_to_user_email', 'invite_token')},
            },
        ),
    ]
