# Generated by Django 3.2.7 on 2021-10-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_alter_invitation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Sent'), (2, 'Accepted'), (3, 'Expired')], null=True, verbose_name='Invite Status'),
        ),
    ]
