# Generated by Django 3.2.7 on 2021-10-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_alter_invitation_invite_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invite_token',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Token'),
        ),
    ]
