# Generated by Django 3.2.7 on 2021-09-11 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=55, null=True, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='description')),
                ('color', models.CharField(blank=True, max_length=6, null=True, verbose_name='board color')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('articles_count', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='articles count')),
                ('last_article_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='board color')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='created user')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': "Board's",
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='created username')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True, unique=True, verbose_name='title slug')),
                ('title', models.CharField(max_length=150, verbose_name='article title')),
                ('content', models.TextField(max_length=550, unique=True, verbose_name='content')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='', verbose_name='article image')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], default='p', max_length=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('views_counts', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('board', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.board', verbose_name='article board')),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='created user')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': "Article's",
                'ordering': ('id',),
            },
        ),
    ]
