# Generated by Django 3.2.7 on 2021-09-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='board color'),
        ),
    ]
