# Generated by Django 3.2.7 on 2021-09-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_board_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='board color'),
        ),
    ]
