# Generated by Django 3.2.7 on 2021-09-12 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_board_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='last_article_title',
        ),
        migrations.AddField(
            model_name='article',
            name='votes_counts',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=120, null=True, unique=True, verbose_name='title slug'),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
    ]
