# Generated by Django 3.2.7 on 2021-09-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210912_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='votes_counts',
        ),
        migrations.AddField(
            model_name='article',
            name='comments_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='comments count'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes_counts',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='likes count'),
        ),
        migrations.AlterField(
            model_name='article',
            name='views_counts',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='viewers count'),
        ),
        migrations.AlterField(
            model_name='board',
            name='last_article_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='last article title'),
        ),
    ]
