# Generated by Django 3.2.7 on 2021-09-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_board_last_article_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='last_article_date',
        ),
        migrations.RemoveField(
            model_name='board',
            name='last_article_id',
        ),
        migrations.RemoveField(
            model_name='board',
            name='last_article_posted_by',
        ),
        migrations.RemoveField(
            model_name='board',
            name='last_article_title',
        ),
    ]
