# Generated by Django 3.2.7 on 2021-09-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210912_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='article is deleted on'),
        ),
    ]
