# Generated by Django 3.2.7 on 2021-09-19 16:44

import dev.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210919_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_edited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=dev.blog.models.article_cover_upload_dir, verbose_name='article image'),
        ),
    ]
