# Generated by Django 3.2.7 on 2021-09-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_articlecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments_count',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='reply_to_this',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies_to_article_comments', to='blog.articlecomment'),
        ),
    ]
