# Generated by Django 3.2.7 on 2021-09-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210927_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='comments count'),
        ),
    ]
