# Generated by Django 3.2.7 on 2021-10-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_article_comment_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'ordering': ('id',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
