# Generated by Django 3.2.7 on 2021-10-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_articlecomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='content',
            field=models.TextField(max_length=450),
        ),
    ]
